all:
	gcc -o programaTrab *.c -g -lm -Wall -Werror
run:
	./programaTrab
teste:
	./programaTrab < ../CasosTestes/10.in
	# ./programaTrab < ../CasosTestes/2.in > ../CasosTestes/t.out 
debug:
	gdb ./programaTrab 
clean:
	rm -f ./programaTrab